### ISSUE TITLE
Upgrade to Docusaurus 3.x

### ISSUE THREAD

**Issue by soulmachine** [soulmachine/algorithm-essentials#12]
Need to upgrade most packages in package.json, especially docusaurus to the latest 3.x version. I tried `ncu -u` to upgrade all packages including docusaurus, but there are a lot of latext related errors, which are probably related to  `rehype-katex` and `remark-math`

**Comment by soulmachine** [comment]
`/reward 200`

**Comment by Niharika0104** [comment]
@soulmachine 
![image](https://github.com/user-attachments/assets/e2201de8-708c-4479-bf2e-9f32620d3290)
Can we close this issue ? 
This is a mandatory step in claiming bounty
